// <auto-generated />
using Altairis.ShirtShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Altairis.ShirtShop.Data.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20171004185410_Add_Order_Dates")]
    partial class Add_Order_Dates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Altairis.ShirtShop.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DatePaid");

                    b.Property<DateTime?>("DateSent");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ShirtSizeId");

                    b.Property<int?>("ShirtTypeIdId");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.HasIndex("ShirtSizeId");

                    b.HasIndex("ShirtTypeIdId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Altairis.ShirtShop.Data.ShirtSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Price");

                    b.Property<int>("SortPriority");

                    b.HasKey("Id");

                    b.ToTable("ShirtSizes");
                });

            modelBuilder.Entity("Altairis.ShirtShop.Data.ShirtType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SortPriority");

                    b.HasKey("Id");

                    b.ToTable("ShirtTypes");
                });

            modelBuilder.Entity("Altairis.ShirtShop.Data.Order", b =>
                {
                    b.HasOne("Altairis.ShirtShop.Data.ShirtSize", "ShirtSize")
                        .WithMany()
                        .HasForeignKey("ShirtSizeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Altairis.ShirtShop.Data.ShirtType", "ShirtTypeId")
                        .WithMany()
                        .HasForeignKey("ShirtTypeIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
