// <auto-generated />
using Altairis.ShirtShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Altairis.ShirtShop.Data.Migrations
{
    [DbContext(typeof(ShirtDbContext))]
    [Migration("20170905231421_Add_PhoneNumber")]
    partial class Add_PhoneNumber
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Altairis.ShirtShop.Data.DeliveryMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Price");

                    b.Property<int>("SortPriority");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMethods");
                });

            modelBuilder.Entity("Altairis.ShirtShop.Data.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BuyerNotes")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DatePaid");

                    b.Property<DateTime?>("DateShipped");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(200);

                    b.Property<int>("DeliveryMethodId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9);

                    b.Property<string>("SellerNotes")
                        .HasMaxLength(1000);

                    b.Property<int>("ShirtModelId");

                    b.Property<int>("ShirtSizeId");

                    b.HasKey("OrderId");

                    b.HasIndex("DeliveryMethodId");

                    b.HasIndex("ShirtModelId");

                    b.HasIndex("ShirtSizeId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Altairis.ShirtShop.Data.ShirtModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SortPriority");

                    b.HasKey("Id");

                    b.ToTable("ShirtModels");
                });

            modelBuilder.Entity("Altairis.ShirtShop.Data.ShirtSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Price");

                    b.Property<int>("SortPriority");

                    b.HasKey("Id");

                    b.ToTable("ShirtSizes");
                });

            modelBuilder.Entity("Altairis.ShirtShop.Data.Order", b =>
                {
                    b.HasOne("Altairis.ShirtShop.Data.DeliveryMethod", "DeliveryMethod")
                        .WithMany()
                        .HasForeignKey("DeliveryMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Altairis.ShirtShop.Data.ShirtModel", "Model")
                        .WithMany()
                        .HasForeignKey("ShirtModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Altairis.ShirtShop.Data.ShirtSize", "Size")
                        .WithMany()
                        .HasForeignKey("ShirtSizeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
